name: ip_address
description: This packages allow you get your public IP Address and many others info about it.
version: 1.0.0
homepage: https://github.com/kagouda/ip_address

environment:
  sdk: '>=2.16.0 <3.0.0'


dependencies:
  http: 

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
