name: ip_address
description: get your public IP address or geographical details from any given IP.
version: 1.0.0
homepage: https://github.com/kagouda/ip_address

environment:
  sdk: '>=2.16.0 <3.0.0'


dependencies:
  http: 

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
